name: Release GoFSUtil

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (major, minor, patch) Ex: 1.0.0'
        required: true
  repository_dispatch:
    types: [auto-release-workflow]

jobs:
  csm-release:
    uses: dell/common-github-actions/.github/workflows/csm-release-libs.yaml@main
    with:
      version: ${{ github.event.client_payload.version }}
