name: Auto Release

on:
  repository_dispatch: # Trigger from another repository
    types: [auto-release-workflow]

jobs:
  release-workflow:
    uses: dell/common-github-actions/.github/workflows/csm-release-libs.yaml@main
