name: Release GoFSUtil
# Invocable as a reusable workflow
# Can be manually triggered
on:
  workflow_call:
    inputs:
      version:
        description: 'Version to release (major, minor, patch) Ex: 1.0.0'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (major, minor, patch) Ex: 1.0.0'
        required: true
  repository_dispatch: # Trigger from another repository
    types: [auto-release-workflow]

jobs:
  csm-release:
    uses: dell/common-github-actions/.github/workflows/csm-release-libs.yaml@main
    name: Release Go Client Libraries
    with:
      version: ${{ github.event.client_payload.version }}
