name: Release GoFSUtil

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (major, minor, patch) Ex: 1.0.0'
        required: true
  repository_dispatch:
    types: [auto-release-workflow]

jobs:
  increment-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ github.client_payload.version }}
  csm-release:
    needs: increment-version
    uses: dell/common-github-actions/.github/workflows/csm-release-libs.yaml@main
    name: Release Go Client Libraries
    with:
      version: ${{ needs.increment-version.outputs.version }}
    secrets: inherit
