name: Release GoFSUtil

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (major, minor, patch) Ex: 1.0.0'
        required: true
  repository_dispatch:
    types: [auto-release-workflow]

jobs:
  csm-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from payload
        id: extract_version
        run: echo "Version:${{ github.event.client_payload.version }}"

      - name: Trigger reusable workflow
        uses: dell/common-github-actions/.github/workflows/csm-release-libs.yaml@main
        with:
          version: ${{ github.event.client_payload.version }}
